### ISSUE TITLE
SSE flags?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#1]
https://github.com/ilyakurdyukov/jpeg-quantsmooth/blob/fb02bb23999e5986ea6340d262556e59feec0d4e/quantsmooth.h#L48-L62

Maybe?:

```c
#if defined(__SSE_USE__)
#if defined(__SSE4_1__)
#define USE_SSE2
#define USE_SSE4
#include <smmintrin.h>
#elif defined(__SSE2__)
#define USE_SSE2
#include <emmintrin.h>

#define _mm_cvtepu8_epi16(a) _mm_unpacklo_epi8(a, _mm_setzero_si128())
// _mm_cmplt_epi16(a, _mm_setzero_si128()) or _mm_srai_epi16(a, 15)
#define _mm_cvtepi16_epi32(a) _mm_unpacklo_epi16(a, _mm_srai_epi16(a, 15))
#define _mm_abs_epi16(a) ({ \
	__m128i __tmp = _mm_srai_epi16(a, 15); \
	_mm_xor_si128(_mm_add_epi16(a, __tmp), __tmp); })
#endif
#endif
```
Pass `__SSE_USE__` from the` Makefile`:
```make
CFLAGS ?= -Wall -D__SSE_USE__ -O2 -march=native -fopenmp
```
And add to docs alternative:
```sh
make CFLAGS="-Wall -O2"
```

PS: Debian Wheezy. I feel better without SSE.

**Comment by ilyakurdyukov** [comment]
Code with SSE2 is a way faster and supported in base x86_64 system.
You can build with specific flags, if you want no SSE:
`make LIBS="-ljpeg -lm" CFLAGS="-fopenmp -static -O3 -mno-sse2" clean all`
See "release.sh" for examples.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>See "release.sh" for examples.

Hmm. It may be worth adding to README (Build section):
```sh
make CFLAGS="-fopenmp -O2 -mno-sse2" clean all
```

PS: The definition of `__SSE_USE__` is still convenient. No harm.

**Comment by ilyakurdyukov** [comment]
Well, I'm kind of bad with documentation. I will be happy if someone help me do it better. But if you write a ready changes to README, and not a subject to add. Also need some edit because of bad English.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>Also need some edit because of bad English.

Да я сам такой же (https://translate.google.ru/). Ты хоть бы профиль посмотрел.

Делай "по образцу", например: https://github.com/ImageProcessing-ElectronicPublications/pixel-art-maker

**Comment by ilyakurdyukov** [comment]
> Да я сам такой же (https://translate.google.ru/). Ты хоть бы профиль посмотрел.

Оно и по нику всё понятно, но нас и другие могут читать (чтобы несколько раз не спрашивали на разных языках).

**Comment by zvezdochiot** [comment]
На всякий: Я без https://translate.google.ru/ в English полный 0 (даже простейшего предложения не выдам). Поэтому прими совет по копипасте, меня оно в основном выручает.

**Comment by ilyakurdyukov** [comment]
Зачем мне дефайнить `__SSE_USE__`? Пользователь не должен делать дефайны такого вида (с подчёркиваниями), это системные. Идея в том, чтобы использовались фичи максимально возможные из разрешённых компилятору. Хорошо бы сделать динамический выбор в зависимости от результата cpuid, но я не хочу сейчас этим заморачиваться.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>Зачем мне дефайнить __SSE_USE__?

Так я ж для примера. На твоё усмотрение. Конструкция простая: сделал и забыл. Предполагается, что сборка будет через `make` с флагами по умолчанию. А остальное - это для "избранных", вроде меня.

**Comment by zvezdochiot** [comment]
С дугой стороны, вопрос в принципе решён. Только в README постарайся добавить.

Fixed https://github.com/ilyakurdyukov/jpeg-quantsmooth/issues/1#issuecomment-578493432

**Comment by ilyakurdyukov** [comment]
> С дугой стороны, вопрос в принципе решён. Только в README постарайся добавить.

Напрягает меня писать README на английском (и на русском бы тоже напрягало, как и любая документация, но меньше), а если переводить гугл транслейтом, то получится филиал алиэкспресс. Так что как-нибудь дополню, когда будет настроение с переводом возиться.
