### ISSUE TITLE
Port for libiio?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#10]
How about porting functions to libiio (https://github.com/mnhrdt/iio)?

**Comment by ilyakurdyukov** [comment]
I'm not interested in this library. But I can try to make a patch for OpenCV (cause it's reader is based on libjpeg-turbo). I think it will be much better this way.

**Comment by zvezdochiot** [comment]
It's a pity. IPOL (http://www.ipol.im/) uses libiio.

**Comment by ilyakurdyukov** [comment]
Давай с объяснениями, для чего используется iio и кто такие IPOL, потому что первый раз о ней слышу. И почему ты хочешь именно для этой библиотеки.

**Comment by zvezdochiot** [comment]
IPOL - журнал такой хитрый (в виде статей и исходных кодов к ним). Ссылку я собственно оставил. Публикует методы денойса и "зрения" изображений. Многие авторы пользуют либу `iio` в своих кодах.

Смотри также https://github.com/IPOL-Fork
