### ISSUE TITLE
graphical interface

### ISSUE THREAD

**Issue by mrkaban** [ilyakurdyukov/jpeg-quantsmooth#11]
Are you planning a graphical interface?

**Comment by zvezdochiot** [comment]
Additional dependencies? Bad!

"It's like asking a GUI to cjpeg."

See https://github.com/ilyakurdyukov/jpeg-quantsmooth/commit/dc80c889c51ea2e9e0bfcdd63585e7d106f65da2#commitcomment-37308741 (will be a library, screw it wherever you want).

**Comment by mrkaban** [comment]
Why make a quality product for everyone? it’s easier to make the product only for a narrow circle of people and spam it on OpenNet. I close the ticket and unsubscribe.

**Comment by ilyakurdyukov** [comment]
If you haven't noticed, @zvezdochiot is not an author. So don't be mad at me.

I'm thinking about of how to make it more useful for Windows users. But not a GUI, something like drag'n'drop JPEG file into link to executable, then a dialog will be displayed for selecting the output filename and location.

So, I'm not very familiar with GUIs, so don't expect something bigger than that from me. If you experienced with GUIs - you can make a fork with GUI.

Also, I'm thinking to explore possibilities to make a plugins for image viewers. But there's a problem, that image viewers may not allow to redefine image loaders for types they know (such as JPEG).

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>I'm not very familiar with GUIs

Do you need it? Everything is inhibited there (there is a price for everything).

**Comment by zvezdochiot** [comment]
@mrkaban say:
>Why make a quality product for everyone?

Лохотрон.

**Comment by s-r-grass** [comment]
> @mrkaban говорят:
> 
> > Зачем делать качественный продукт для всех?
> 
> Лохотрон.

Лохотрон, это репозитории, который нах*р никому не нужны, например, Ваши, ни единого лайка. И тем не менее, звездочиот чувствует себя умный и крутым программистом.

Но гениальней всего отвечать человеку, который отписался)))) зачем тогда тут мусоришь своим д***мом изо рта, на стену покричи, такой же эффект будет.

**Comment by s-r-grass** [comment]
Even the simplest graphical interface adds * x looks. In other words, popularity will grow at times. You can insert ads and get paid for it.

Даже простейший графический интерфейс добавляет *х посмотров. Иными словами популярность вырастит в разы. Можно будет вставить рекламу и получать денежку за неё.

**Comment by ilyakurdyukov** [comment]
You haven't even written a GUI for which OS you want?

I'm a strongly backend programmer, even in the days when I worked on Windows - I used very few and simple interfaces, and mostly the command line.

The web version is already made, but ugly. Because I'm not an HTML designer.
Linux is fine without a GUI, most of Linux programs are command-line.
I don't have any OSX devices. I have no experience with Android GUI-s (only native libraries).
I can make my own Windows dialog, but it will be just as ugly as the web version.

**Comment by s-r-grass** [comment]
> You haven't even written a GUI for which OS you want?
> 
> I'm a strongly backend programmer, even in the days when I worked on Windows - I used very few and simple interfaces, and mostly the command line.
> 
> The web version is already made, but ugly. Because I'm not an HTML designer.
> Linux is fine without a GUI, most of Linux programs are command-line.
> I don't have any OSX devices. I have no experience with Android GUI-s (only native libraries).
> I can make my own Windows dialog, but it will be just as ugly as the web version.

Judging by his repositories, he was talking about Windows.

**Comment by ilyakurdyukov** [comment]
Okay, I can make a minimal GUI wrapper for Windows.

**Comment by zvezdochiot** [comment]
@s-r-grass say:
>это репозитории, который нах*р никому не нужны

У тебя и таких нет, товариш спамер.

**Comment by s-r-grass** [comment]
> @s-r-grass say:
> 
> > это репозитории, который нах*р никому не нужны
> 
> У тебя и таких нет, товариш спамер. Сбили автора. Теперь он вместо того, чтоб прорабатывать прогу, будет ковыряться с Вашим Гуем.

Про спамера писал не я, учись читать. Также научись считать, по всей видимости, даже до двух считать не умеешь) 
Далее, если тебе интересно продолжить беседу, продолжи со стенкой, я пойду с женой погуляю. Отписываюсь)

**Comment by zvezdochiot** [comment]
@s-r-grass say;
>Отписываюсь)

Наконец то. Скатертью дорожка.

**Comment by ilyakurdyukov** [comment]
I made it work, but there are some missing features:

- dynamically select SSE/AVX
- show console output
- unicode support for filenames
- drag'n'drop support
- remember options
- progress indicator

I'll release it later with some improvements from this list (not all).

**Comment by ilyakurdyukov** [comment]
Made a copy of the web version, but on WinAPI. You can download from releases. No progress indicator for now, also needs an icon, but that's for later.
