### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#12]
Илья. Думаю удалить форк https://github.com/ImageProcessing-ElectronicPublications/jpeg-quantsmooth , так как в нём теперь мало смысла (сам буду заниматься только https://github.com/ImageProcessing-ElectronicPublications/libjpegqs ). Но так как это "общественное", желательно твоё "добро". Мне этот форк больше не нужен, ты вроде как его уже изучил. Добро?

**Comment by ilyakurdyukov** [comment]
Удаляй.

**Comment by zvezdochiot** [comment]
Окей.

**Comment by ilyakurdyukov** [comment]
libjpegqs - это что ты задумал, сборку как библиотеки?

**Comment by zvezdochiot** [comment]
Библиотека под линь. С виндой туго, у меня под рукой нет. MMX и пр. стрепанул нафиг, так как это не для меня.

**Comment by ilyakurdyukov** [comment]
У меня винда в VirtualBox живёт.

**Comment by zvezdochiot** [comment]
У меня и для виртуалки места нема. Всё забито под завязку и всё нужное. Книги и журналы съедают диски на раз.

**Comment by zvezdochiot** [comment]
Вопрос кстати интересует: А PellesC (http://www.smorgasbordet.com/pellesc/) твой проект компилирует?

**Comment by ilyakurdyukov** [comment]
Я только Clang-ом еще иногда проверяю. Можешь сам проверить.
Так то у меня в мейкфалах -Wall -Wextra -pedantic, так что должно компилироваться в номральных компиляторах. MSVC не в счёт.

**Comment by zvezdochiot** [comment]
Ну гуд. Не помню насколько он вменяемый, но в стародавние времена, когда под окнами сидел, компилял именно им. Проверить к сожалению не могу.
