### ISSUE TITLE
libjpeg8-dev?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#13]
```sh
make SIMD=none all
```
```make
cc -Wall -O2  -DNO_SIMD -c -o libjpegqs.o libjpegqs.c
In file included from libjpegqs.c:28:0:
/usr/include/jpeglib.h:1150:55: fatal error: jpegint.h: Нет такого файла или каталога
compilation terminated.
make: *** [libjpegqs.o] Ошибка 1
```
`jpegint.h` : `libjpeg62-dev` - YES, `libjpeg8-dev` - NO.

`libjpeg8-dev` : `/usr/include/jpeglib.h` (end file): 
```c
#ifdef JPEG_INTERNALS
#include "jpegint.h"		/* fetch private declarations */
#include "jerror.h"		/* fetch error codes too */
#endif
```

**Comment by zvezdochiot** [comment]
Not support.

**Comment by ilyakurdyukov** [comment]
You need to build libjpeg from sources, because linux packages sometimes doesn't include "jpegint.h", so that's why I'm written a lot of instructions in README how to build libjpeg from sources. Also, this file needs only for static library `make lib`, not for application `make app`.

**Comment by ilyakurdyukov** [comment]
Should work with last commit.

**Comment by zvezdochiot** [comment]
Да я уже пакеты пересобрал. Чортовы майнтайнеры.

**Comment by ilyakurdyukov** [comment]
https://bugs.launchpad.net/libjpeg-turbo/+bug/898395
То и дело кто-то забывает про этот файл, в пакетах msys2/mingw тоже было замечено. Я скопировал к себе из jpegint.h всё что мне нужно, эти вещи стабильны между версиями.
