### ISSUE TITLE
Use library?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#14]
https://github.com/ilyakurdyukov/jpeg-quantsmooth/blob/5de5f75c82e05c380d3cf46ec79b09359c5e8e15/Makefile#L121-L122

Maybe?:
```make
$(APPNAME): $(SRCNAME) lib$(APPNAME).a
	$(CC) $(CFLAGS_APP) -DAPPNAME=$(APPNAME) -s -o $@ $< -Wl,--gc-sections $(JPEGLIB2) lib$(APPNAME).a -lm
```

**Comment by ilyakurdyukov** [comment]
No, application uses different object files with logs and TRANSCODE_ONLY defined.

**Comment by zvezdochiot** [comment]
The library too. How so?

**Comment by ilyakurdyukov** [comment]
Библиотека для чтения или транскодирования (jpeg -> jpeg), приложение только для транскодирования, но с логами. Если я буду совмещать, то при линковке будут ненужные зависимости.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>Если я буду совмещать, то при линковке будут ненужные зависимости.

То есть "ты проверил" и у тебя получилась "шляпа"? Я то просто не пользую SIMD и у меня никакой "шляпы" не получается. Наоборот всё осмыслено, всё гуд.

**Comment by ilyakurdyukov** [comment]
Библиотека используется также для чтения jpeg -> RGB, и при статической линковке тянет функции для чтения из libjpeg, которые приложению не нужны. А что ты SIMD не используешь - то просто дольше ждёшь, потому что SIMD теперь динамический и вызывается в зависимости от возможностей процессора пользователя (как в libjpeg-turbo к примеру). К тому же в любом amd64 процессоре есть SSE2 просто по умолчанию.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>функции для чтения из libjpeg, которые приложению не нужны.

"Шляпы" я всё равно не вижу. Или эти функции утежеляют win-сборку непомерно?
