### ISSUE TITLE
Separate code and docs?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#15]
Maybe move `{*.c,*.h}` in `src/`?

**Comment by ilyakurdyukov** [comment]
Я не буду заниматься вкусовщиной, и перекладывать файлы просто потому, что кому-то так нравится. Такие вещи я сделаю только когда мне этого захочется.

**Comment by zvezdochiot** [comment]
Ок. (просто спросил).
