### ISSUE TITLE
Arithmetic coded JPG

### ISSUE THREAD

**Issue by TPS** [ilyakurdyukov/jpeg-quantsmooth#18]
@ilyakurdyukov I've used QuantSmooth via IrfanView & noticed that it isn't currently compatible with arithmetic coded jpgs.  Are there plans to implement that?

**Comment by zvezdochiot** [comment]
@TPS say:
>it isn't currently compatible with arithmetic coded jpgs.

What kind of "incompatibility"?

**Comment by ilyakurdyukov** [comment]
This is actually just because the plugin is linked to libjpeg with the arithmetic encoder disabled.

**Comment by TPS** [comment]
Currently, Irfanview crashes whenever loading an arithmetic JPG while QuantSmooth is enabled, but loads them normally when QS is disabled. (I've already e-mailed IV's dev, but can't find a way to directly @ him here.)

**Comment by TPS** [comment]
> This is actually just because the plugin is linked to libjpeg with the arithmetic encoder disabled.

@ilyakurdyukov Is there a technical reason for that, or could it be resolved as simply as relinking with such support re-enabled? Also, do you mean base libjpeg or libjpeg-turbo?  (Or isn't there a difference anymore?  I haven't tracked that in a little while.)

**Comment by ilyakurdyukov** [comment]
> @ilyakurdyukov Is there a technical reason for that, or could it be resolved as simply as relinking with such support re-enabled? Also, do you mean base libjpeg or libjpeg-turbo? (Or isn't there a difference anymore? I haven't tracked that in a little while.)

I can rebuild with arithmetic decoder enabled.
libjpeg-turbo is supported.

**Comment by ilyakurdyukov** [comment]
Check `jpegqs_irfanview.zip` in releases (x64 version in "x64" folder). I also sent a copy to Irfan.

**Comment by TPS** [comment]
@ilyakurdyukov That solved it perfectly.  Thanks! 🙇🏾‍♂️

**Comment by TPS** [comment]
@ilyakurdyukov Just to be clear, is the IV plugin you sent built against libjpeg-turbo or libjpeg?

**Comment by ilyakurdyukov** [comment]
libjpeg, may work with both, as said. (and should be compatible with mozjpeg also)
