### ISSUE TITLE
Prog name?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#2]
https://github.com/ilyakurdyukov/jpeg-quantsmooth/blob/fb02bb23999e5986ea6340d262556e59feec0d4e/Makefile#L7-L15

Maybe?:
```make
PNAME = jpegqs
...
all: $(PNAME)

clean:
	rm -rf $(PNAME)

$(PNAME): quantsmooth.h idct.h

$(PNAME): quantsmooth.c
	$(CC) $(CFLAGS) -s -o $@ $< $(LIBS)
```
And:
https://github.com/ilyakurdyukov/jpeg-quantsmooth/blob/fb02bb23999e5986ea6340d262556e59feec0d4e/quantsmooth.c#L185
To:
```c
	const char *progname = argv[0], *fn;
```

**Comment by ilyakurdyukov** [comment]
I'll change it over time. I'm more thinking about: 1) improving quality, 2) improving performance, 3) actual bugs?.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>I'll change it over time.

Ok.

**Comment by ilyakurdyukov** [comment]
Added similar changes, but with define named "APPNAME".

**Comment by zvezdochiot** [comment]
`quantsmooth` is too long and does not indicate the basic nature of the program. Less bad is `jpegqs`.

Fixed: https://github.com/ilyakurdyukov/jpeg-quantsmooth/commit/67bac148178cde08b762cfbcfd4798c90176c93b
