### ISSUE TITLE
force `DCT coefficient out of range`?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#27]
Hi @ilyakurdyukov .

Libjpeg out `DCT coefficient out of range`. The file is not processed (output 0). The file is viewed and converted.

**Comment by zvezdochiot** [comment]
Sorry. Already fixed.

**Comment by zvezdochiot** [comment]
Hi @ilyakurdyukov .

No. Not fixed. At you it is even worse (appearance of result). Example:

![10002](https://github.com/ilyakurdyukov/jpeg-quantsmooth/assets/12370082/e5949318-94e1-4a24-aeaf-d110a6bd583c)

![10002 bad](https://github.com/ilyakurdyukov/jpeg-quantsmooth/assets/12370082/c36e7b79-2f04-40e1-89f3-e2404e671225)

**Comment by ilyakurdyukov** [comment]
Fixed in https://github.com/ilyakurdyukov/jpeg-quantsmooth/commit/87accb68226cb665dc7aa80d363d4ff4333781e9.

**Comment by ilyakurdyukov** [comment]
`libjpeg` corrupts the image when it sees a coefficient that goes beyond the limit - it doesn't crop it and doesn't save the rest of the image.

**Comment by zvezdochiot** [comment]
Hi @ilyakurdyukov .

Release? New?
