### ISSUE TITLE
Alternative links?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#3]
Maybe add alternative links?:
* https://github.com/victorvde/jpeg2png
* https://github.com/google/knusperli

**Comment by ilyakurdyukov** [comment]
Maybe, I'll see how these projects related with mine in terms of quality and speed.
**jpeg2png** (already tested this) is a significantly slower and little blurry, but better on very low JPEG quality (which no one will actually use). Maybe options can change something, but I tried only default mode.
**knusperli** looks no good at deblocking, even on examples from README.md. I need to take a closer look.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>Maybe

Ok.

**Comment by ilyakurdyukov** [comment]
**knusperli** is absolutely useless, I wonder why did Google post thing that bad in their github.
It work so bad, that you can hardly notice difference between input and output when zooming in.
Its processing time is little slower than **quantsmooth** (with AVX and OpenMP), but **knusperli** is completely unoptimized. Probably, **knusperli** can be greatly faster with optimizations, but its effect is so small that it makes no sense to use it.

**Comment by ilyakurdyukov** [comment]
Here you go. I have added alternatives and comparison.

**Comment by zvezdochiot** [comment]
Very good.

Fixed: https://github.com/ilyakurdyukov/jpeg-quantsmooth/commit/c643e9f4a1f7c24851e03f19644aced021a76fd6
