### ISSUE TITLE
New Nodejs package?

### ISSUE THREAD

**Issue by SrJSDev** [ilyakurdyukov/jpeg-quantsmooth#30]
Hello! I looked through the web wasm code, but wondered if you could publish an npm nodejs package instead. Would be fantastic!

I'm currently trying to implement a solution in sharp using convolution matrix for a surface blur, but the results aren't great so far. This lib would be waaay better! :)

Or maybe you know of an npm package that's already available? Thanks!

**Comment by ilyakurdyukov** [comment]
Sorry, I'm not a JS programmer and have never done anything with Node.js.

**Comment by SrJSDev** [comment]
Ok thanks
