### ISSUE TITLE
The name of the utility.

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#6]
Is it allowed to rename a utility from `quantsmooth` to` jpegqs` in a fork (https://github.com/ImageProcessing-ElectronicPublications/jpeg-quantsmooth)? For me, the original name is inconvenient.

**Comment by ilyakurdyukov** [comment]
In your fork, you can do whatever you think is necessary, as long as it doesn't violate the program license. You can change the name, just leave a link to original code in README.

**Comment by zvezdochiot** [comment]
Ok.
