### ISSUE TITLE
roundf(x)

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#7]
https://github.com/ilyakurdyukov/jpeg-quantsmooth/blob/4c381e37fbfb8c7947d25a1a9761c281267d8202/quantsmooth.h#L20-L22

Maybe?:

```c
#ifdef NO_MATH_LIB
static inline float roundf(float x)
{
    return (float)((int)((x < 0.0) ? (x - 0.5f) : (x + 0.5f))) ;
}
static inline float fabsf(float x)
{
    return ((x < 0.0) ? -x : x);
}
#endif
```
Or do I not understand something?

**Comment by ilyakurdyukov** [comment]
That is used to build with no "-lm". Compiler generate an assembly instruction for fabsf(), but not for roundf(). As I doesn't documented this define - thus it's not look as an issue for me.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>That is used to build with no "-lm".

Yes. But `static inline` is faster than `#define`.

**Comment by ilyakurdyukov** [comment]
roundf() implementation does not have a noticeable impact on the performance of this program.

**Comment by zvezdochiot** [comment]
As you say. It’s not my business.
