### ISSUE TITLE
MP3 DCT quant smooth?

### ISSUE THREAD

**Issue by zvezdochiot** [ilyakurdyukov/jpeg-quantsmooth#9]
Interested in MP3 DCT Quantum Smooth based on madplay (https://www.underbit.com/products/mad/) or mpg123 (https://www.mpg123.de/).

I immediately warn the obvious answer: I know about filter banks. I don’t propose to mess with “filter banks” for dequantization, but I suggest using other information.

“Volume War” in combination with “filter banks” in any MP3 without additional regulation (REPLAY_GAIN) leads to clipping. It is this fact that I propose to use for dequantizing MP3.

I’m not sure that the result of dequantization can be saved in MP3 (even 320kbps), but the utilities I have specified allow to save the result in WAV.

PS: This time expected `library + tool`.

**Comment by ilyakurdyukov** [comment]
I'm not as familiar with audio processing, as with image processing. Not sure, that MP3 quantization is alike. I found research work [here](https://www.researchgate.net/publication/224054729_A_high_quality_re-quantizationquantization_method_for_MP3_and_MPEG-4_AAC_audio_coding), that maybe do this thing, maybe not. But can't find a link to read it for free to be sure.

**Comment by zvezdochiot** [comment]
>I found research work here, that maybe do this thing, maybe not.

We will help. Torrents are everything. The topic is important!

"Имя, сестра, имя?!"

**Comment by zvezdochiot** [comment]
Google our everything.

https://thomasmunroblog.files.wordpress.com/2016/03/a-high-quality-re-quantization-quantization-method-for-mp3-and-mpeg-4-aac-audio-coding.pdf

**Comment by ilyakurdyukov** [comment]
Look like it's about smaller lookup tables and performance, at same quality.

**Comment by zvezdochiot** [comment]
I will not prompt. I'm used to sndfile. For me, MP3 is gibberish for now.

**Comment by zvezdochiot** [comment]
Maybe added label "Help wanted"?

**Comment by ilyakurdyukov** [comment]
Try to ask for this [here](https://github.com/lieff/minimp3). I'm not sure if this is possible, because I have no experience with MP3 decoders.

**Comment by zvezdochiot** [comment]
Ok.
